# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

<<<<<<< HEAD
# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# the HTML language tag › https://www.w3.org/International/questions/qa-choosing-language-tags
lang: en-US

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Pacific/Auckland

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Max van Dijck                          # the main title

tagline: Aspiring Machine Learning Practitioner   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Max van Dijck, Aspiring Machine Learning Practitioner
  and Data Science.
=======
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ''

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Additional parameters for datetime localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Chirpy                          # the main title

tagline: A text-focused Jekyll theme   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  A minimal, responsive, and powerful Jekyll theme for presenting professional writing.
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ''

github:
<<<<<<< HEAD
  username: MaxVanDijck             # change to your github username

twitter:
  username: Max_vanDijck            # change to your twitter username
=======
  username: github_username             # change to your github username

twitter:
  username: twitter_username            # change to your twitter username
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
<<<<<<< HEAD
  name: Max van Dijck
  email: vandijcksm@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/Max_vanDijck      # change to your twitter homepage
    - https://github.com/MaxVanDijck      # change to your github homepage
=======
  name: your_full_name
  email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/username       # change to your github homepage
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

<<<<<<< HEAD
google_site_verification: google_meta_tag_verification # change to your verification string
# --------------------------

google_analytics:
  id: ''              # fill in your Google Analytics ID
=======
google_site_verification:               # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id:                 # fill in your Google Analytics ID
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
<<<<<<< HEAD
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: ./assets/img/portrait.jpg
=======
img_cdn: 'https://raw.githubusercontent.com/cotes2020/chirpy-images/main'

# the avatar on sidebar, support local or CORS resources
avatar: '/commons/avatar.jpg'
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

# boolean type, the global switch for ToC in posts.
toc: true

<<<<<<< HEAD
disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'Max'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
=======
comments:
  active:         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:             # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:          # optional, default to 'pathname'
    input_position:   # optional, default to 'bottom'
    lang:             # optional, default to the value of `site.lang`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:      # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env:          # [development|production]

pwa:
  enabled: true   # the option for PWA feature
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

<<<<<<< HEAD

defaults:
  -
    scope:
=======
defaults:
  - scope:
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
<<<<<<< HEAD
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
=======
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
<<<<<<< HEAD
      dynamic_title: true    # Hide title in mobile screens.
=======
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
<<<<<<< HEAD
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'
=======
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json
>>>>>>> ad137fa2945b1870b9c1dd5e9212a5f4af7c3580

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
